config/routes.rb
Rails.application.routes.draw do
  # Routes without api subdomain for staging env
  namespace :api, path: '/api' do
    api_version(:module => "V1", :header => {:name => "Accept", :value => "application/vnd.copapi.com+json; version=1"}) do
      resources :hits, only: [:index, :show, :create]
    end
  end
  get 'map', to:'map#map'
  get 'charts', to:'charts#chart'
  get 'index',to:'home#index'
  get 'search', to:'search#search'
  root :to => 'home#index'
  devise_for :users
end

app/models/hit.rb
# == Schema Information
#
# Table name: hits
#
#  id            :integer          not null, primary key
#  name          :string
#  last          :string
#  phone         :string
#  latitude      :string
#  longitud      :string
#  report        :string
#  contact_name  :string
#  contact_last  :string
#  contact_phone :string
#  contact_email :string
#  age           :integer
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Hit < ActiveRecord::Base
  belongs_to :user
  validates :phone, :longitud, :latitude, :report, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                                :integer          not null, primary key
#  email                             :string           default(""), not null
#  encrypted_password                :string           default(""), not null
#  reset_password_token              :string
#  reset_password_sent_at            :datetime
#  remember_created_at               :datetime
#  sign_in_count                     :integer          default("0"), not null
#  current_sign_in_at                :datetime
#  last_sign_in_at                   :datetime
#  current_sign_in_ip                :string
#  last_sign_in_ip                   :string
#  created_at                        :datetime
#  updated_at                        :datetime
#  user_type                         :string           default("citizen")
#  name                              :string
#  lastname                          :string
#  phone                             :string
#  birthdate                         :date
#  gender                            :string
#  address_1                         :string
#  address_2                         :string
#  address_zip_code                  :string
#  address_state                     :string
#  address_country                   :state
#  emergency_contact_name            :string
#  emergency_contact_phone           :string
#  emergency_contact_alternate_phone :string
#  emergency_contact_relation        :string
#  warranty_number                   :string
#

# user_type can be:
#    - admin
#    - citizen
#    - policeman

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :user_type, :gender, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_relation, presence: true

  has_many :hits

  def admin?
    self.user_type == "admin"
  end

  def citizen?
    self.user_type == "citizen"
  end

  def policeman?
    self.user_type == "policeman"
  end
end

app/controllers/api/v1/base_controller.rb
class API::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  respond_to :json

  def authenticate
    authenticate_token || render_unauthorized
  end

  def authenticate_token
    authenticate_with_http_token do |token,options|
      @authenticated_user = User.find_by(auth_token: token)
    end
  end

  def render_unauthorized
    self.headers['WWW-Authenticate'] = 'Token realm="Application"'
    render json: { errors: ['Unauthorized'] }, status: 401
  end

  def authenticated_user
    @authenticated_user
  end
  helper_method :authenticated_user

  def match_route_with_authenticated_user
    unless authenticated_user.id == params[:id].to_i || authenticated_user.id == params[:user_id].to_i
      render json: { user:  { errors: ["User id doesn't match the user authenticated by the token"]}}, status: 422
    end
  end

  def per_page_param(per_page, default)
    unless per_page
      return default
    end
    return per_page.to_i
  end

  def pagination_json(paginated_array, per_page)
    size = paginated_array.size
    total_pages = (size.to_f/per_page.to_f).ceil
    { pagination: { per_page: per_page, total_pages: total_pages, total_objects: size } }
  end
end

app/controllers/api/v1/hits_controller.rb
class Api::V1::HitsController < API::V1::BaseController
  def index
    
    hits = Hit.all
     if params[:minTime]
    hits = hits.where("created_at > ?", params[:minTime].to_datetime)
    if params[:maxTime]
      hits = hits.where("created_at < ?", params[:maxTime].to_datetime)
    end
    end
    if params[:minLat] and params[:maxLat]
    hits = hits.where("latitude > ? AND latitude < ?", params[:minLat], params[:maxLat])
    end
    if params[:minLong] and params[:maxLong]
      hits = hits.where("longitud > ? AND longitud < ?", params[:minLong], params[:maxLong])
    end
    if params[:report]
    hits = hits.where("report LIKE ?", params[:report])
    end
    render json: hits, each_serializer: HitSerializer, status: 200
  end

  def show
    
  end

  def create
  
    hit = Hit.new(hit_params)

    if hit.save
      render json: hit, serializer: HitSerializer, status: 200
    else
      render json: { hit: { errors: hit.errors.full_messages } }, status: 422
    end
  end

  private

  def hit_params
    params.require(:hit).permit(:minLat, :maxLat, :minLong, :maxLong, :report, :minTime, :maxTime, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #rescue_from CanCan::AccessDenied do |exception|
    #flash[:error] = message
    #redirect_to redirect_path
  #end

  ##Can-Can fix for Strong parameters in rails 4
  #before_filter do
    #resource = controller_path.singularize.gsub('/', '_').to_sym
    #method = "#{resource}_params"
    #params[resource] &&= send(method) if respond_to?(method, true)
  #end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def chart
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/map_controller.rb
class  MapController < ApplicationController
  def map
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def Search
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def show
  end
end

app/helpers/api/v1/hits_helper.rb
module Api::V1::HitsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charts/chart.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Copapi</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Copapi
                    </a>
                </li>
                <li>
                    <%=link_to "Report Feed", index_path,:class => "btn btn-default", :method => :get %> 
                </li>
                <li>
                    <%=link_to "Search", search_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Crime Map", map_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Charts", charts_path,:class => "btn btn-default", :method => :get %>
                </li>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
							<p>Charts</p>
							<div id="bar"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
        console.log("hello");
	});

	var options = {
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Crimes by type'
        },
        xAxis: {
			categories: ["Murder", "Rape", "Theft", "Robbery", "Mugging", "Car theft"]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Occurrences',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: ' millions'
        },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -40,
            y: 100,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: [{
            data: [0,0,0,0,0,0]
        }]
	};

	$.ajax({
		url: './api/hits',
    	headers: {
    		'Accept': 'application/vnd.copapi.com+json; version=1',
    	},
    	dataType: 'json',
    	success: function(data){
    		var datarr = data.hits;
			$(datarr).each(function(){
				var item = $(this)[0];
				if (item.report == 'Murder')
						options.series[0].data[0]++;
				else if (item.report == 'Rape')
						options.series[0].data[1]++;
				else if (item.report == 'Theft')
						options.series[0].data[2]++;
				else if (item.report == 'Robbery')
						options.series[0].data[3]++;
				else if (item.report == 'Mugging')
						options.series[0].data[4]++;
				else if (item.report == 'Car theft')
						options.series[0].data[5]++;
			});
			$('#bar').highcharts(options);
		}
	});
    // Receives array of JSON reports
    function drawer(data){
        data.each(function(){
            var html ='<div style="border: 5px solid black" class="container">';
            html += '<p>Report:'+$(this).report+'</p>';
            html +='<p>Contact Phone:'+$(this).phone+'</p>';
            html +='<p>Name:'+$(this).name+'</p>';
            html +='<%=link_to "Map", map_path,:class => "btn btn-default", :method => :get %></div>';
        });
    }

    
     
    </script>

</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Copapi</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Copapi
                    </a>
                </li>
                <li>
                    <%=link_to "Report Feed", index_path,:class => "btn btn-default", :method => :get %> 
                </li>
                <li>
                    <%=link_to "Search", search_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Crime Map", map_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Charts", charts_path,:class => "btn btn-default", :method => :get %>
                </li>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
					<h1 id="feed-header">Report Feed</h1>	
					<div id="feed"></div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    var mostRecentTime=0;
    var shownIds=[];
    setInterval(function(){
       $.ajax({
          url: './api/hits',
          headers: {
            'Accept': 'application/vnd.copapi.com+json; version=1',
          },
          dataType: 'json',
          success: function(data){
            var datarr = data.hits;
            datarr = $.grep(datarr, function(n, i){
                console.log(n.firstname);
                if (($.inArray(n.id, shownIds)) >= 0){
                    return false;
                }
                else{
                    // console.log("hey")
                    shownIds.push(n.id);
                    return true;
                }
            });
            mostRecentTime = $(datarr).first().timestamp;
            drawer(datarr);
          }
        }); 
    },2000);
    // Receives array of JSON reports
    function drawer(data){

        $(data).each(function(){
            var item = $(this)[0];
            // console.log(item);
            var html ='<div class="report" class="container">';
			html += '<p><b>Report:</b> '+ item.report+'</p>';
			html +='<p><b>Phone:</b> '+ item.phone+'</p>';
			html +='<p><b>Name:</b> '+ item.firstname + ' ' + item.lastname + '</p>';
            var link = '<a href="http://maps.google.com?q=' + item.lat + ',' + item.long + '\">Location</a>'; 
            html += link;
            // html +='<%=link_to "Map", map_path,:class => "btn btn-default", :method => :get %></div>';
            $("#feed").prepend(html).hide().fadeIn();
        });
    }

    
     
    </script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Copapi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

 <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/map/map.html.erb
<!DOCTYPE html>

  <head>
    <meta charset="utf-8">
    <title>Heatmaps</title>
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      #panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=visualization"></script>
    <script>
var map, pointarray, heatmap;

var taxiData = [];
$.ajax({
	url: './api/hits',
    headers: {
    	'Accept': 'application/vnd.copapi.com+json; version=1',
    },
    dataType: 'json',
    success: function(data){
    	var datarr = data.hits;
		$(datarr).each(function(){
			var item = $(this)[0];
			console.log(item);
			var newPoint = new google.maps.LatLng(item.lat, item.long);
			taxiData.push(newPoint);	
		});
	}
}); 
		
function initialize() {
  var mapOptions = {
	zoom: 16,
    center: new google.maps.LatLng(41.830068, -71.399720),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };

  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  var pointArray = new google.maps.MVCArray(taxiData);

  heatmap = new google.maps.visualization.HeatmapLayer({
    data: pointArray
  });

  heatmap.setMap(map);
}

function toggleHeatmap() {
  heatmap.setMap(heatmap.getMap() ? null : map);
}

function changeGradient() {
  var gradient = [
    'rgba(0, 255, 255, 0)',
    'rgba(0, 255, 255, 1)',
    'rgba(0, 191, 255, 1)',
    'rgba(0, 127, 255, 1)',
    'rgba(0, 63, 255, 1)',
    'rgba(0, 0, 255, 1)',
    'rgba(0, 0, 223, 1)',
    'rgba(0, 0, 191, 1)',
    'rgba(0, 0, 159, 1)',
    'rgba(0, 0, 127, 1)',
    'rgba(63, 0, 91, 1)',
    'rgba(127, 0, 63, 1)',
    'rgba(191, 0, 31, 1)',
    'rgba(255, 0, 0, 1)'
  ]
  heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
}

function changeRadius() {
  heatmap.set('radius', heatmap.get('radius') ? null : 20);
}

function changeOpacity() {
  heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>

  <body>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Copapi
                    </a>
                </li>
                <li>
                    <%=link_to "Report Feed", index_path,:class => "btn btn-default", :method => :get %> 
                </li>
                <li>
                    <%=link_to "Search", search_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Crime Map", map_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Charts", charts_path,:class => "btn btn-default", :method => :get %>
                </li>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <div id="panel">
		<button onclick="changeGradient()">Change gradient</button>
		<button onclick="changeRadius()">Change radius</button>
		<button onclick="changeOpacity()">Change opacity</button>
	</div>
	<div id="map-canvas"></div>
  </body>

app/views/search/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Copapi</title>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
         <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Copapi
                    </a>
                </li>
                <li>
                    <%=link_to "Report Feed", index_path,:class => "btn btn-default", :method => :get %> 
                </li>
                <li>
                    <%=link_to "Search", search_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Crime Map", map_path,:class => "btn btn-default", :method => :get %>
                </li>
                <li>
                    <%=link_to "Charts", charts_path,:class => "btn btn-default", :method => :get %>
                </li>
                </li>
            </ul>
        </div>
        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Search 
                            <small>Browse crime reports</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-file"></i> Search
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">

                       <!-- <form role="form">-->

                        <div class="col-xs-2">
                            <div class="form-group">
                                <label>Type</label>
                                <input class="form-control" id="type" placeholder="e.g. 'Assault'">
                            </div>
                        </div>

                        <div class="col-xs-2">
                            <div class="form-group">
                                <label>Longitude</label>
                                <input class="form-control" id="longitud" placeholder="e.g. '10293849'">
                            </div>
                        </div>

                        <div class="col-xs-2">
                            <div class="form-group">
                                <label>Latitude</label>
                                <input class="form-control" id="latitud" placeholder="e.g. '-94843323'">
                            </div>
                        </div>

                        <div class="col-xs-2">
                            <div class="form-group">
                                <label>Date</label>
                                <input class="form-control" id="minDate" placeholder="e.g. '08/11/12'">
                            </div>
                        </div>

                        <div class="col-xs-2">
                            <div class="form-group">
                                <label>to</label>
                                <input class="form-control" id="maxDate" placeholder="e.g. '08/11/12'">
                            </div>
                        </div>



                        <div class="form-group">
                            <br>
                            <button type="submit" class="btn btn-search" onclick="buttonClicked()">Search</button>
                        </div>

                       <!-- </form>-->
                        <div id="feed-search"></div>


                    </div>

                </div>


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

</body>

</html>